
# Use VM based build environment
sudo: required
dist: trusty

language: java
jdk:
    - openjdk8
    - openjdk9
    - openjdk11

   matrix:
    - jdk: openjdk8
    
    branches:
  only:
    - master 
   

env:
  global:
    - MAVEN_OPTS="-Xmx10244M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

cache:
  directories:
      - '$HOME/.m2/repository'

before_script:
# This seems to be required to get travis to set Xmx4g, per https://github.com/travis-ci/travis-ci/issues/3893
  - export MAVEN_SKIP_RC=true
# Sometimes things get restored from the cache with bad permissions. See https://github.com/travis-ci/travis-ci/issues/9630
  - sudo chmod -R 777 "$HOME/.m2/repository";
  - sudo chown -R travis:travis "$HOME/.m2/repository";

script:
  - mvn -B install